update to release 2.1.0 GA

diff --git a/bfrec b/bfrec
--- a/bfrec
+++ b/bfrec
@@ -27,13 +27,239 @@
 # of the authors and should not be interpreted as representing official policies,
 # either expressed or implied, of the FreeBSD Project.
 
-bfb_location=/lib/firmware/mellanox/default.bfb
+set -e
 
-# If default.bfb doesn't exist, we're not on install.bfb, so
-# fall back to the hardware bfb contained in mlxbf-bootimages.
-if [ ! -f "$bfb_location" ]; then
-    bfb_location=/lib/firmware/mellanox/boot/default.bfb
+# To debug set run=echo
+run=
+
+PROGNAME=$(basename "$0")
+
+usage()
+{
+    cat <<EOF
+Usage: $PROGNAME    [--help]
+                    [--default [FILE]]
+                    [--capsule [FILE]]
+EOF
+    exit 0
+}
+
+default_mode=
+capsule_mode=
+
+PARSED_OPTIONS=`getopt -n "$PROGNAME" -o h \
+                    -l help,default,capsule -- "$@"`
+eval set -- "$PARSED_OPTIONS"
+
+while true
+do
+  case $1 in
+      -h | --help)
+          usage
+          ;;
+      -d | --default)
+          default_mode=1
+          shift
+          ;;
+      -c | --capsule)
+          capsule_mode=1
+          shift
+          ;;
+      --)
+          shift
+          break
+          ;;
+  esac
+done
+
+if [ -n "$default_mode" ] && [ -n "$capsule_mode" ]; then
+    cat <<EOF
+ERROR: Use either options '--default' or '--capsule'
+EOF
+    exit 1
 fi
 
-mlxbf-bootctl -s -d /dev/mmcblk0 -b $bfb_location
-mlxbf-bootctl -s -d /dev/mmcblk0 -b $bfb_location
+bfb_location=/lib/firmware/mellanox/boot
+capsule_location=/lib/firmware/mellanox/boot/capsule
+
+exit_failure()
+{
+    action=$1
+    path=$2
+    [[ -n "$action" ]] && \
+        (echo "use $2 path to update boot partitions."; $action; exit $?)
+
+    exit 2
+}
+
+uefi_capsule_update()
+{
+    # Set firmware update application variables
+    updater_efi=FirmwareUpdate.efi
+    updater_desc="FirmwareUpdater"
+    # Set EFI System partition mountpoint
+    mount_efi=/mnt/efi_system_partition
+    # Set capsule update file variable name
+    capsule_efi=MmcBootCap
+    device_efi=/dev/mmcblk0p1
+
+    # First, check whether UEFI supports capsule update. Note that UEFI
+    # Capsule update is supported in UEFI version 2.0 or greater.
+    bfver=/opt/mlnx/scripts/bfver
+    uefi_ver=$($bfver | grep UEFI | cut -d':' -f2 | sed -e 's/[[:space:]]//')
+    uefi_ver_major=$(echo $uefi_ver | cut -d'.' -f1)
+    [[ $((uefi_ver_major)) -lt 2 ]] &&
+        (echo "Capsule update isn't supported in UEFI version $uefi_ver"; \
+         exit_failure $1 $2)
+
+    # UEFI will read the capsule image from the EFI System Partition.
+    # Check whether an EFI System partition is present. If not, then
+    # the capsule update is not supported;
+    [[ ! $(fdisk -l | grep "EFI System") ]] && \
+        (echo "cannot find EFI System Partition"; exit_failure $1 $2)
+
+    [[ ! -f "$capsule_location/$updater_efi" ]] && \
+        (echo "cannot find EFI updater application"; exit_failure $1 $2)
+
+    capsule_file=$capsule_location/$capsule_efi
+    if [ ! -f "$capsule_file" ]; then
+        echo "cannot find Capsule $capsule_file"
+        # Use the default.bfb file as capsule file. This might be
+        # reviewed once the UEFI capsule format is used.
+        capsule_file=$bfb_location/default.bfb
+        if [ -f "$capsule_file" ]; then
+            echo "use $capsule_file as Capsule file"
+        else
+            echo "no Capsule update file found"
+            exit_failure $1 $2
+        fi
+    fi
+
+    # Check whether the EFI System Partition is mounted. If not mounted,
+    # then create the mountpoint and mount the disk partition to the
+    # default location in order to copy the update files.
+    esp_dir=$(mount | grep $device_efi | cut -f 3 -d' ')
+    if [ -z "$esp_dir" ]; then
+        if [ ! -d $mount_efi ]; then
+            $run mkdir $mount_efi
+        fi
+        $run mount $device_efi $mount_efi
+    else
+        mount_efi=$esp_dir
+    fi
+
+    # Copy the capsule file into the EFI System Partition. Rename the file
+    # to match the expected pathname in UEFI, if needed.
+    $run cp $capsule_file $mount_efi/$capsule_efi
+    $run cp $capsule_location/$updater_efi $mount_efi/$updater_efi
+    $run sync
+
+    # Doing some cleanup, if needed
+    if [ -z "$esp_dir"  ]; then
+        $run umount $mount_efi
+        $run rmdir $mount_efi
+        # Wait until eMMC internal cache is fully flushed
+        $run sleep 3
+    fi
+
+    # Create a boot entry to process the capsule update.
+    efivars=/sys/firmware/efi/efivars
+    test "$(ls -A $efivars)" || mount -t efivarfs efivarfs $efivars
+
+    # The UEFI boot device selector must boot the EFI updater application
+    # to enter the system firmware update mode.
+
+    if [ "$(efibootmgr | grep $updater_desc)" ]; then
+        option=$(efibootmgr | grep $updater_desc | cut -f1 -d'*' | cut -c5-)
+        $run efibootmgr -b "$option" -B
+    fi
+
+    disk=$(echo $device_efi | cut -f 1 -d'p')
+    part=$(echo $device_efi | cut -f 2 -d'p')
+    $run efibootmgr -c -d $disk -p $part \
+        -L "$updater_desc" -l "$updater_efi" 2>&1 >/dev/null
+
+    cat <<EOF
+
+    ***********************************************************************
+    ***                                                                 ***
+    ***    Reboot the system to process the platform firmware updates   ***
+    ***                                                                 ***
+    ***********************************************************************
+
+EOF
+
+    ## Ask if the user wishes to reboot?
+    #read -p 'Reboot now (Y/n) [n]: ' answer
+    #if [ "$answer" == 'Y' ]; then
+    #    $run reboot
+    #fi
+    return 0
+}
+
+kernel_bootctl_update()
+{
+    bfb_device=/dev/mmcblk0
+
+    [[ ! $(which mlxbf-bootctl) ]] && \
+        (echo "mlxbf-bootctl program is not supported" ; exit_failure $1 $2)
+
+    [[ ! -b "$bfb_device" ]] && \
+        (echo "bad block device $bfb_device"; exit_failure $1 $2)
+
+    [[ -z "$bfb_file" ]] && bfb_file=$bfb_location/default.bfb
+
+    [[ ! -f "$bfb_file" ]] && \
+        (echo "cannot find $bfb_file file"; exit_failure $1 $2)
+
+    $run /sbin/mlxbf-bootctl -s -d $bfb_device -b $bfb_file
+    $run /sbin/mlxbf-bootctl -s -d $bfb_device -b $bfb_file
+    $run sync
+
+    cat <<EOF
+
+    ***********************************************************************
+    ***                                                                 ***
+    ***                 Platform firmware updates complete.             ***
+    ***                                                                 ***
+    ***********************************************************************
+
+EOF
+
+    return 0
+}
+
+# Parse command arguments
+if [ -n "$default_mode" ]; then
+    bfb_file=
+    if [ $# -eq 1 ]; then
+        bfb_file=$1
+    elif [ $# -ge 2 ]; then
+        echo "too many arguments with option '--default'"
+        exit 1
+    fi
+
+    # Update the boot partitions.
+    kernel_bootctl_update; exit $?
+
+elif [ -n "$capsule_mode" ]; then
+    capsule_file=
+    if [ $# -eq 1 ]; then
+        capsule_file=$1
+    fi
+    if [ $# -ge 2 ]; then
+        echo "too many arguments with option '--capsule'"
+        exit 1
+    fi
+
+    # Initiate UEFI capsule update.
+    uefi_capsule_update; exit $?
+fi
+
+# If we reach here, then try both modes. Start with capsule update path
+# otherwise use the default path.
+next_update_action=kernel_bootctl_update
+next_update_path=default
+
+uefi_capsule_update $next_update_action $next_update_path
+
